# Generated by Django 2.1.4 on 2019-05-23 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs_list', '0004_auto_20181226_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs_list.Song')),
            ],
        ),
        migrations.AlterField(
            model_name='eventsongs',
            name='song_number',
            field=models.IntegerField(null=True),
        ),
    ]
