# Generated by Django 2.1.4 on 2020-02-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs_list', '0005_auto_20190523_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='program',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
