# Generated by Django 2.1.4 on 2022-01-12 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songs_list', '0010_auto_20220104_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='concert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='conductor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='outfit',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
