# Generated by Django 2.1.4 on 2022-01-28 11:42

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songs_list', '0011_auto_20220112_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentSongs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids_of_songs', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('deadline', models.DateField(blank=True)),
                ('expiration_date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField(null=True)),
                ('meeting_link', models.CharField(max_length=255)),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('required_songs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='songs_list.CurrentSongs')),
            ],
        ),
        migrations.AddField(
            model_name='usersong',
            name='user_knows',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evaluationmeeting',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs_list.EvaluationSession'),
        ),
        migrations.AddField(
            model_name='evaluationmeeting',
            name='singer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
