# Generated by Django 2.1.4 on 2022-03-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs_list', '0014_usersong_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userext',
            name='singer',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userext',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
