# Generated by Django 2.1.4 on 2022-03-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs_list', '0015_auto_20220304_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersong',
            name='voice',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
