# Generated by Django 2.1.4 on 2022-07-28 13:35

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs_list', '0016_auto_20220316_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateEventSingers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attenders', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='privateeventsingers',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs_list.Event'),
        ),
    ]
