# Generated by Django 2.2.28 on 2022-12-29 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs_list', '0017_auto_20220728_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationmeeting',
            name='session',
        ),
        migrations.RemoveField(
            model_name='evaluationmeeting',
            name='singer',
        ),
        migrations.RemoveField(
            model_name='evaluationsession',
            name='host',
        ),
        migrations.RemoveField(
            model_name='evaluationsession',
            name='required_songs',
        ),
        migrations.RemoveField(
            model_name='event',
            name='conductor',
        ),
        migrations.RemoveField(
            model_name='event',
            name='songs',
        ),
        migrations.RemoveField(
            model_name='eventsongs',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventsongs',
            name='song',
        ),
        migrations.RemoveField(
            model_name='privateeventsingers',
            name='event',
        ),
        migrations.RemoveField(
            model_name='sessionhosts',
            name='host',
        ),
        migrations.RemoveField(
            model_name='usersong',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='usersong',
            name='user_knows',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='CurrentSongs',
        ),
        migrations.DeleteModel(
            name='EvaluationMeeting',
        ),
        migrations.DeleteModel(
            name='EvaluationSession',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventSongs',
        ),
        migrations.DeleteModel(
            name='PrivateEventSingers',
        ),
        migrations.DeleteModel(
            name='SessionHosts',
        ),
    ]
